### ISSUE TITLE
do future next

### ISSUE THREAD

**Issue by HausemasterIssue** [Gopro336/PyroClient-Deobf#4]
crack or deobf

**Comment by Gopro336** [comment]
> Anyway, in future crack there was different obfuscation. Gopro can only deobfuscate stuff with public deobfuscators. For example, he wouldn't be able to deobfuscate ZKM.

not entirely true

**Comment by Gopro336** [comment]
0x defiantly doesn't use pro guard, Future uses ZKM I believe, possibly with other obfuscations layered on top. Strangely enough, alitori string transformers can partially deobf the strings in future 2.8. Currently future 2.10 does not have a dump or a crack to use, and 2.9 is very outdated, so I don't plan to pursue making a deobf, especially considering public transformers for future don't exist like they do for Binsecure.
